#!/usr/bin/env bash
set -e

SCRIPT_START=$(date +%s)
BM_START=$SCRIPT_START
CPU_COUNT=$(nproc)

function benchmark {
  BM_END=$(date +%s)
  echo $((($BM_END-$BM_START)/60))m $((($BM_END-$BM_START)%60))s
  BM_START=$BM_END
}

cd $(dirname "${BASH_SOURCE[0]}")
echo "Using CPUs: $CPU_COUNT"

QUIET=--quiet

if [ ! -d _download ]; then
    echo -n "Downloading sources... "
    rm -rf _build _download.tmp && mkdir _download.tmp && cd _download.tmp

    wget $QUIET --continue \
        https://busybox.net/downloads/busybox-1.36.1.tar.bz2 \
        https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.15.6.tar.xz

    wget $QUIET --continue -O opensbi-1.7.tar.gz \
        https://github.com/riscv-software-src/opensbi/archive/refs/tags/v1.7.tar.gz

    cd .. && mv _download.tmp _download
    benchmark
fi

mkdir -p _build _ccache && cd _build && BUILD_DIR=$(pwd)

if [ ! -d busybox ]; then
    echo -n "Building busybox... "
    rm -rf busybox.tmp && tar -xf ../_download/busybox-* && mv busybox-* busybox.tmp && cd busybox.tmp

    CROSS_COMPILE=riscv64-linux-gnu- make \
        defconfig > /dev/null 2>&1

    LDFLAGS="--static" CROSS_COMPILE=riscv64-linux-gnu- make \
        --jobs=$CPU_COUNT busybox #> /dev/null 2>&1

    cd .. && mv busybox.tmp busybox
    benchmark
fi

if [ ! -d linux ]; then
    echo -n "Building kernel... "
    rm -rf linux.tmp && tar -xf ../_download/linux-* && mv linux-* linux.tmp && cd linux.tmp

    flags_y=(
        ARCH_RV64I BINFMT_ELF BINFMT_MISC BINFMT_SCRIPT BLK_DEV_INITRD DEBUG_INFO DEBUG_INFO_DWARF5
        DEBUG_KERNEL GDB_SCRIPTS KGDB KGDB_SERIAL_CONSOLE NONPORTABLE RISCV_INTC RISCV_ISA_C
        SERIAL_SIFIVE SERIAL_SIFIVE_CONSOLE SIFIVE_PLIC TIMER_OF
    )

    make $QUIET ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- CC="ccache riscv64-linux-gnu-gcc" \
      allnoconfig

    for f in ${flags_y[@]}; do
        scripts/config --set-val $f y
    done

    make $QUIET ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- CC="ccache riscv64-linux-gnu-gcc" \
      olddefconfig

    make $QUIET ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- CC="ccache riscv64-linux-gnu-gcc" \
      KBUILD_BUILD_TIMESTAMP="Thu Jan 1 00:00:00 UTC 1970" \
      KBUILD_BUILD_USER="builduser" \
      KBUILD_BUILD_HOST="buildhost" \
      $QUIET --jobs=$CPU_COUNT Image

    cd .. && mv linux.tmp linux
    benchmark
fi

if [ ! -d opensbi ]; then
    echo -n "Building opensbi... "
    rm -rf opensbi.tmp && tar -xf ../_download/opensbi-* && mv opensbi-* opensbi.tmp && cd opensbi.tmp

    dtc $QUIET -O dtb -o rv64.dtb ../../rv64.dts

    make $QUIET ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- CC="ccache riscv64-linux-gnu-gcc" \
      PLATFORM=generic PLATFORM_RISCV_XLEN=64 \
      FW_PAYLOAD_PATH=../linux/arch/riscv/boot/Image \
      FW_FDT_PATH=rv64.dtb > /dev/null 2>&1

    cd .. && mv opensbi.tmp opensbi
    benchmark
fi

rm -rf initramfs
if [ ! -d initramfs ]; then
    echo -n "Building initramfs... "
    rm -rf initramfs.tmp && mkdir -p initramfs.tmp/fs && cd initramfs.tmp

    mkdir -p fs/{bin,dev,proc,root,sbin,sys,usr/{bin,sbin}}
    cp ../busybox/busybox fs/bin/
    cp ../../init fs/

    cd fs && find . | cpio --reproducible --quiet --create --owner 0:0 --format newc | gzip -n -c > ../initramfs.cpio.gz && cd ..

    cd .. && mv initramfs.tmp initramfs
    benchmark
fi

echo -n "Total execution time: "
BM_START=$SCRIPT_START && benchmark
