#!/bin/bash
set -euo pipefail
cd $(dirname $0)

docker/build

docker run --rm -ti \
  -v $(pwd)/all:/home/user/output \
  riscv-tests bash -c "
  rm -rf output/isa/* &&
  mkdir -p output/isa/{bin,dump} &&
  cd riscv-target/share/riscv-tests/isa/ && \
  rm Makefile &&
  mv *.dump ~/output/isa/dump/ &&
  find . -name '*-*' -exec riscv64-unknown-elf-objcopy -O binary {} ~/output/isa/bin/{} \;
"
