#!/bin/bash
set -euo pipefail
cd $(dirname $0)

docker build . -t buildroot-rv

docker run --rm \
  -v $(pwd)/output:/home/user/target \
  buildroot-rv \
  bash -c "
    rm -rf ~/target/* &&
    cp ~/output/* ~/target/
  "
