#!/usr/bin/env bash
set -e

SCRIPT_START=$(date +%s)
BM_START=${SCRIPT_START}
CPU_COUNT=$(nproc)
QUIET=--quiet

export CCACHE_DIR=/home/user/cache/cc

function benchmark {
  BM_END=$(date +%s)
  echo $(((${BM_END}-${BM_START})/60))m $(((${BM_END}-${BM_START})%60))s
  BM_START=${BM_END}
}

################################################################################

export ARCH=riscv
export CC="ccache riscv64-unknown-linux-gnu-gcc"
export CFLAGS="-march=rv64imac -mabi=lp64"
export CROSS_COMPILE=riscv64-unknown-linux-gnu-
export SOURCE_DATE_EPOCH=0

echo
echo "Using CPUs: ${CPU_COUNT}"

rm -rf build output && mkdir -p build output cache/{download,cc}

################################################################################

echo -n "Downloading sources... "
cd cache/download

VERSION_BUSYBOX=1.36.1
VERSION_KERNEL=7.1.1
VERSION_OPENSBI=1.8.1
VERSION_GO=1.26.4

if [ ! -f busybox-${VERSION_BUSYBOX}.tar.bz2 ]; then
    rm -rf busybox-*
    wget ${QUIET} https://busybox.net/downloads/busybox-${VERSION_BUSYBOX}.tar.bz2
fi

if [ ! -f linux-${VERSION_KERNEL}.tar.xz ]; then
    rm -rf linux-*
    wget ${QUIET} https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-${VERSION_KERNEL}.tar.xz
fi

if [ ! -f opensbi-${VERSION_OPENSBI}.tar.gz ]; then
    rm -rf opensbi-*
    wget ${QUIET} https://github.com/riscv-software-src/opensbi/archive/refs/tags/v${VERSION_OPENSBI}.tar.gz
    mv v${VERSION_OPENSBI}.tar.gz opensbi-${VERSION_OPENSBI}.tar.gz
fi

if [ ! -f go${VERSION_GO}.linux-riscv64.tar.gz ]; then
    rm -rf go*
    wget ${QUIET} https://go.dev/dl/go${VERSION_GO}.linux-riscv64.tar.gz
fi

cd ~
benchmark

################################################################################

echo -n "Building busybox... "
rm -rf busybox-* build/busybox
tar -xf cache/download/busybox-${VERSION_BUSYBOX}.tar.bz2 && mv busybox-* build/busybox
cd build/busybox

KCONFIG_NOTIMESTAMP=1 \
    make ${QUIET} \
        defconfig \
        > /dev/null 2>&1

sed -i 's/CONFIG_TC=y/CONFIG_TC=n/' .config
sed -i 's/CONFIG_TCPSVD=y/CONFIG_TCPSVD=n/' .config

LDFLAGS="--static ${CFLAGS}" \
    make ${QUIET} \
        CC="${CC}" \
        --jobs=${CPU_COUNT} \
        busybox \
        > /dev/null 2>&1

cd ~
benchmark

################################################################################

echo -n "Building initramfs... "
rm -rf build/initramfs
mkdir -p build/initramfs && cp -R input/initramfs build/initramfs/fs

cd build/initramfs/fs
mkdir -p bin usr/local && cp ~/build/busybox/busybox bin/

find . -exec touch -t 197001010000.00 {} +
find . ! -path . | sort | cpio \
    --reproducible --quiet --create --owner +0:+0 --format newc \
    > ../initramfs.cpio

#tar -C usr/local -xf ~/cache/download/go*
#find usr/local -exec touch -t 197001010000.00 {} +
#find . ! -path . | sort | cpio \
#    --reproducible --quiet --create --owner +0:+0 --format newc \
#    > ../initramfs-go.cpio

#truncate -s 64M ../disk.img
#mkfs.ext4 -U "c1b9d5a2-f162-11cf-9ece-0020afc76f16" -T 0 \
#  -q -O ^has_journal -E root_owner=0:0 -d . ../disk.img

SOURCE_DATE_EPOCH=0 \
  mke2fs -q -t ext4 \
  -d . \
  -U "c1b9d5a2-f162-11cf-9ece-0020afc76f16" \
  -O ^has_journal \
  -E hash_seed="c1b9d5a2-f162-11cf-9ece-0020afc76f16" \
  ../disk.img 64M

mv ../disk.img ~/output/

cd ~
benchmark

################################################################################

echo -n "Building kernel... "
rm -rf linux-* build/kernel
tar -xf cache/download/linux-${VERSION_KERNEL}.tar.xz && mv linux-* build/kernel

cd build/kernel

flags_y=(
    ARCH_RV64I
    SERIAL_SIFIVE SERIAL_SIFIVE_CONSOLE
    BLK_DEV BLK_DEV_INITRD INITRAMFS_COMPRESSION_NONE
    DEVTMPFS DEVTMPFS_MOUNT
    BINFMT_ELF BINFMT_SCRIPT
)

make ${QUIET} \
    allnoconfig

for f in ${flags_y[@]}; do
    scripts/config --set-val ${f} y
done

#BUILDS=("" "-go")
BUILDS=("")

for SUFFIX in "${BUILDS[@]}"; do
  scripts/config --set-val INITRAMFS_SOURCE \"/home/user/build/initramfs/initramfs${SUFFIX}.cpio\"

  make ${QUIET} \
      olddefconfig

  make ${QUIET} \
      CC="${CC}" \
      KBUILD_BUILD_HOST="buildhost" \
      KBUILD_BUILD_TIMESTAMP="Thu Jan 1 00:00:00 UTC 1970" \
      KBUILD_BUILD_USER="builduser" \
      --jobs=${CPU_COUNT} \
      Image

  mv arch/riscv/boot/Image Image${SUFFIX}
  gzip -9 -n -c Image${SUFFIX} > ~/output/kernel${SUFFIX}.gz
done

cd ~
benchmark

################################################################################

echo -n "Building opensbi... "
rm -rf opensbi-* build/opensbi
tar -xf cache/download/opensbi-${VERSION_OPENSBI}.tar.gz && mv opensbi-* build/opensbi
cd build/opensbi

dtc ${QUIET} \
  -O dtb \
  -o ~/output/rv.dtb \
  ~/input/rv.dts

make clean

make ${QUIET} \
  CC="${CC}" \
  FW_DYNAMIC=y \
  PLATFORM=generic \
  PLATFORM_RISCV_XLEN=64 \
  --jobs=${CPU_COUNT} \
  > /dev/null 2>&1

gzip -9 -n -c build/platform/generic/firmware/fw_dynamic.bin > ~/output/opensbi.gz

cd ~
benchmark

################################################################################

sha256sum -b \
  build/busybox/busybox \
  build/initramfs/initramfs*.cpio \
  build/kernel/Image* \
  output/* > output/sha256.txt

echo -n "Total execution time: "
BM_START=${SCRIPT_START} && benchmark
