#!/usr/bin/env sh
set -e
cd $(dirname "$0")

../toolchain/build

rm -rf container.cid output/*

docker run -ti \
    --cidfile container.cid \
    --volume $(pwd)/input:/home/user/input \
    --mount type=volume,src=biko-cache,dst=/home/user/cache \
    rv-toolchain \
    bash input/build

docker cp --quiet $(cat container.cid):/home/user/output/sha256.txt output/

docker rm $(cat container.cid) > /dev/null && rm -rf container.cid
