#!/bin/busybox sh
/bin/busybox --install -s
mkdir -p /dev /proc /run /sys /tmp /var/log /var/run
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mkdir -p /dev/pts && mount -t devpts devpts /dev/pts
echo rv > /proc/sys/kernel/hostname
chown user:user /home/user
exec /sbin/init
