#!/bin/bash
set -euo pipefail
cd $(dirname $0)

./start || true

docker exec buildroot bash -c "
  git checkout 2024.02.13 &&

  mkdir -p ~/extern/tmp/download && export BR2_DL_DIR=~/extern/tmp/download &&

  echo -e '\n\n (1) config \n\n' &&
    (make BR2_EXTERNAL=~/extern rv_defconfig ||
      (echo -e '\n\n (1) failed \n\n' && false)) &&

  echo -e '\n\n (2) make \n\n' &&
    (make ||
      (echo -e '\n\n (2) failed \n\n' && false)) &&

  echo -e '\n\n (3) rebuild \n\n' &&
    (make linux-rebuild opensbi-rebuild all ||
      (echo -e '\n\n (3) failed \n\n' && false)) &&

  echo -e '\n\n (4) output \n\n' &&
    gzip -c output/images/fw_payload.bin > output/images/fw_payload.bin.gz &&
    rm -rf ~/extern/bin/* &&
    cp output/images/{fw_payload.bin.gz,rv.dtb} ~/extern/bin/ &&

  echo -e '\n\n (5) success \n\n'
"
