#!/usr/bin/env sh
set -e
cd $(dirname "$0")

rm -rf output/*

toolchain/build

docker run -ti --rm \
    -v $(pwd)/work:/home/user/work \
    --user $(id -u):$(id -g) \
    rv-toolchain \
    bash build

gzip -9 -n -c work/_build/opensbi/build/platform/generic/firmware/fw_payload.bin > output/rv64.kernel.gz

sha256sum -b \
  work/_download/* \
  work/_build/busybox/busybox \
  work/_build/initramfs/initramfs.cpio \
  work/_build/kernel/arch/riscv/boot/Image\
  work/_build/opensbi/build/platform/generic/firmware/fw_payload.bin\
  output/rv64.kernel.gz > output/sha256.txt
