#!/bin/busybox sh
/bin/busybox mkdir -p /dev /dev/pts /home/user /mnt /proc /root /run /sbin /sys /tmp /usr/bin /usr/sbin /var/log /var/run
/bin/busybox --install -s
chmod a+rwx /tmp
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts devpts /dev/pts
mount -t ext4 -o dax /dev/pmem0 /mnt
echo rv > /proc/sys/kernel/hostname
chown user:user /home/user
exec /sbin/init
